# Generated by Django 3.2.1 on 2024-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240516_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='Contact',
            field=models.CharField(default='SOME STRING', max_length=30)
        )
    ]
